feat: impl animation
suzuka-kosen-festa/2024-hp pull request #149
Opened 2024-06-30 17:20 UTC by re-taro

close #76 
close #109

2024-06-30 18:35 UTC, Bayathy commented
![image](https://github.com/suzuka-kosen-festa/2024-hp/assets/68783260/3f81ab15-b9f1-4ccb-a0e0-95a08f2a74eb)
この「Tap to Start」がガタガタになるのってどうにもならんのだっけ

2024-06-30 18:42 UTC, re-taro commented
文字の太さ的にどうしようもない。ちょっと調整します

2024-06-30 19:04 UTC, re-taro commented
消したほうが見やすいわ

2024-07-01 00:29 UTC, shiron-dev requested changes
<img width="833" alt="スクリーンショット 2024-07-01 9 24 13" src="https://github.com/suzuka-kosen-festa/2024-hp/assets/54439127/ce2c529c-685c-4025-898d-36b66d28453d">
原因不明で再現性がないですが、時々Daysが000の状態で画面で止まります。普通のリロードでは治らず、スーパーリロードで治ります
(これとは別件で、ページを読み込んだ瞬間に一瞬真っ暗になったり、一瞬000と表示されたりするのが気になったり...こっちのプライオリティは低いです)

<img width="1796" alt="スクリーンショット 2024-07-01 9 28 50" src="https://github.com/suzuka-kosen-festa/2024-hp/assets/54439127/b99930c4-a410-4291-9aed-010c70029244">
また、この画面のDAYS、ちょっと見にくくね？ってなってます。デザインより文字が潰れてる...?

2024-07-01 00:59 UTC, Bayathy commented
これFIgma上だとそんなアレではないんだけどねぇ、消しちゃっても大丈夫です

2024-07-01 02:32 UTC, re-taro commented
> <img alt="スクリーンショット 2024-07-01 9 24 13" width="833" src="https://private-user-images.githubusercontent.com/54439127/344503733-ce2c529c-685c-4025-898d-36b66d28453d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDEzMDksIm5iZiI6MTcxOTgwMTAwOSwicGF0aCI6Ii81NDQzOTEyNy8zNDQ1MDM3MzMtY2UyYzUyOWMtNjg1Yy00MDI1LTg5OGQtMzZiNjZkMjg0NTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDAyMzAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4NTg5ZmY5MWIxYWRiN2MxOTE5ODI2YTliODg3ZWRmZmE1YWU4OTZmZDgxZjgyNmU2NmUwNzAyNDc5ZmY1YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T3Dx0ImtbRdW-hfKvJYctjdTjtd0BOTMG2pLey9F85c"> 原因不明で再現性がないですが、時々Daysが000の状態で画面で止まります。普通のリロードでは治らず、スーパーリロードで治ります (これとは別件で、ページを読み込んだ瞬間に一瞬真っ暗になったり、一瞬000と表示されたりするのが気になったり...こっちのプライオリティは低いです) 

@shiron-dev 
これねぇ再現性がないと対応が難しいですね。issueには切ります。

> <img alt="スクリーンショット 2024-07-01 9 28 50" width="1796" src="https://private-user-images.githubusercontent.com/54439127/344504015-b99930c4-a410-4291-9aed-010c70029244.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDEzMDksIm5iZiI6MTcxOTgwMTAwOSwicGF0aCI6Ii81NDQzOTEyNy8zNDQ1MDQwMTUtYjk5OTMwYzQtYTQxMC00MjkxLTlhZWQtMDEwYzcwMDI5MjQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDAyMzAwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczMzY1YmM0MWQ1NThhMTAxOGEzZDU4NmQ3Mzg0NDYwOGU2MjU4ZGM2ODI2M2Q5MjczZjc0MTNjNDBjMGYzZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Zr07HTeucv33Aa4Eda5LzCAcGsYmtklUptqWRUlR30o"> また、この画面のDAYS、ちょっと見にくくね？ってなってます。デザインより文字が潰れてる...?

@shiron-dev @Bayathy 
これはGSAP(というよりJSアニメーション)が悪さをしていてsvgが壊れるんですよね。再現性◯なんですけど修正方法が立っていません。

2024-07-01 04:38 UTC, re-taro commented
原因はわかりました。修正できるか検討します

> @shiron-dev @Bayathy
これはGSAP(というよりJSアニメーション)が悪さをしていてsvgが壊れるんですよね。再現性◯なんですけど修正方法が立っていません。

2024-07-01 04:53 UTC, re-taro commented
修正ed

2024-07-01 05:37 UTC, shiron-dev requested changes
> 原因不明で再現性がないですが、時々Daysが000の状態で画面で止まります。普通のリロードでは治らず、スーパーリロードで治ります

悪化しました

2024-07-01 05:39 UTC, re-taro commented
> > 原因不明で再現性がないですが、時々Daysが000の状態で画面で止まります。普通のリロードでは治らず、スーパーリロードで治ります
> 
> 悪化しました

これがちでどういう経路で起こっているか教えてほしいかも

2024-07-01 05:48 UTC, re-taro commented
あーSSR時にGSAPのコードを読みに行って死んでCSRに切り替わっているからか。ちょっと確認しますね

2024-07-01 05:49 UTC, shiron-dev commented
plainなchrom(バージョン: 126.0.6478.127（Official Build） （arm64）)でスーパーリロードすると二回に一回ぐらい発生します。適当にリロードすればほぼほぼ再現できるので.har等々どんな情報でも提供できます。

あと、サブリミナル効果みたいに一瞬だけHeroページが表示されるのも若干気になる。

https://github.com/suzuka-kosen-festa/2024-hp/assets/54439127/e20969f2-3ca4-45da-9f09-8c09ceb53d53

2024-07-01 06:24 UTC, shiron-dev requested changes
アニメーション中に連打するとバグる

Uploading 画面収録 2024-07-01 15.23.48.mov…

2024-07-01 06:28 UTC, re-taro commented
> アニメーション中に連打するとバグる
> 
>  2024-07-01.15.23.48.mov

これは僕が実装サボったからですねwww

修正します

2024-07-01 08:49 UTC, shiron-dev approved these changes

2024-07-01 12:49 UTC, shiron-dev approved these changes

2024-07-01 13:05 UTC, ka1ut submitted a review, later dismissed
👍

2024-07-01 21:50 UTC, shiron-dev approved these changes

2024-07-02 01:28 UTC, nao0228 approved these changes
lgtm お疲れ様です

2024-07-02 01:29 UTC, merged