feat: 🚀 学科展示カードの作成
suzuka-kosen-festa/2024-hp pull request #449
Opened 2024-10-17 05:52 UTC by Bayathy

Close #431

2024-10-19 15:11 UTC, re-taro requested changes

2024-10-19 15:11 UTC, re-taro commented on app/routes/bazar/features/ExhibitionCard/styles.css.ts
> +export const borderColor = createVar();
[must]

君等はどこで使われているのだろうか。要らないから消そう。

2024-10-20 05:20 UTC, Bayathy commented on app/routes/bazar/features/ExhibitionCard/styles.css.ts
> +export const borderColor = createVar();
[2f5e296](https://github.com/suzuka-kosen-festa/2024-hp/pull/449/commits/2f5e29628440e69a244ed5d86a56e3180e516dea)

2024-10-20 05:25 UTC, re-taro approved these changes
![LGTM](https://looks-to.me/images/posts/thl1mh2w4gfdoffqo4w5n7vu)

2024-10-20 05:25 UTC, merged